export type Severity = "high" | "medium" | "low";

export type RedFlag = {
  phrase: string;
  category: string;
  severity: Severity;
  explanation: string;
};

const flag = (
  phrase: string,
  category: string,
  severity: Severity,
  explanation: string,
): RedFlag => ({ phrase, category, severity, explanation });

const group = (
  phrases: string[],
  category: string,
  severity: Severity,
  explanation: string,
): RedFlag[] => phrases.map((phrase) => flag(phrase, category, severity, explanation));

const baseRedFlags: RedFlag[] = [
  flag("sei troppo sensibile", "Svalutazione", "high", "Sminuisce una reazione emotiva invece di ascoltarne la causa."),
  flag("te la prendi per tutto", "Svalutazione", "medium", "Trasforma un disagio specifico in un difetto generale."),
  flag("stai esagerando", "Svalutazione", "medium", "Riduce la legittimità di ciò che senti o descrivi."),
  flag("non è niente", "Svalutazione", "low", "Minimizza un problema senza valutarne l'impatto su di te."),
  flag("fai sempre drammi", "Svalutazione", "high", "Etichetta le emozioni come teatro per evitare il confronto."),
  flag("sei ridicolo", "Svalutazione", "high", "Attacca la persona invece di discutere il comportamento."),
  flag("sei patetico", "Svalutazione", "high", "Usa il disprezzo per indebolire autostima e posizione."),
  flag("non sai stare allo scherzo", "Svalutazione", "medium", "Giustifica un'offesa attribuendo il problema alla tua reazione."),
  flag("era solo una battuta", "Svalutazione", "medium", "Minimizza l'effetto di parole offensive appellandosi all'intenzione."),
  flag("rilassati", "Svalutazione", "low", "Può liquidare un'emozione senza affrontare ciò che l'ha provocata."),
  flag("calmati", "Svalutazione", "low", "Può delegittimare il tono invece di rispondere al contenuto."),
  flag("sei fuori di testa", "Gaslighting", "high", "Mette in dubbio la tua lucidità per screditare la tua versione."),
  flag("te lo sei inventato", "Gaslighting", "high", "Nega direttamente la tua esperienza o memoria."),
  flag("non è mai successo", "Gaslighting", "high", "Cancella un evento riportato senza aprire un confronto sui fatti."),
  flag("ricordi male", "Gaslighting", "medium", "Insinua che la tua memoria sia inaffidabile senza elementi concreti."),
  flag("ti stai immaginando tutto", "Gaslighting", "high", "Presenta la tua percezione come fantasia."),
  flag("sei paranoico", "Gaslighting", "high", "Medicalizza o deride un dubbio per evitare di rispondervi."),
  flag("sei pazzo", "Gaslighting", "high", "Usa un'etichetta sulla salute mentale per invalidare la persona."),
  flag("non ho mai detto questo", "Gaslighting", "medium", "Può negare parole precedenti e confondere la ricostruzione."),
  flag("hai capito male", "Gaslighting", "medium", "Sposta automaticamente l'errore sulla tua comprensione."),
  flag("stai distorcendo tutto", "Gaslighting", "medium", "Accusa la tua versione senza chiarire fatti o differenze."),
  flag("è tutto nella tua testa", "Gaslighting", "high", "Nega la realtà del tuo disagio attribuendolo solo alla mente."),
  flag("nessuno ti crederebbe", "Intimidazione", "high", "Tenta di isolarti facendo leva sulla paura di non essere creduto."),
  flag("tutti pensano che tu sia", "Pressione sociale", "high", "Invoca un consenso non verificabile per metterti in minoranza."),
  flag("lo dicono tutti", "Pressione sociale", "medium", "Usa un gruppo indefinito come autorità contro di te."),
  flag("sono tutti d'accordo con me", "Pressione sociale", "medium", "Sostituisce il merito dell'argomento con una presunta maggioranza."),
  flag("nessuno ti sopporta", "Isolamento", "high", "Colpisce il senso di appartenenza e può aumentare la dipendenza."),
  flag("solo io posso capirti", "Isolamento", "high", "Si presenta come unica fonte di comprensione per creare dipendenza."),
  flag("i tuoi amici ti mettono contro di me", "Isolamento", "high", "Scredita la rete di supporto e favorisce l'isolamento."),
  flag("la tua famiglia è tossica", "Isolamento", "medium", "Può servire a recidere legami senza analizzare comportamenti specifici."),
  flag("non raccontarlo a nessuno", "Segretezza", "high", "Impone segretezza e riduce la possibilità di chiedere supporto."),
  flag("questa cosa resta tra noi", "Segretezza", "medium", "Può creare pressione a nascondere un comportamento problematico."),
  flag("se mi amassi davvero", "Ricatto emotivo", "high", "Condiziona l'amore all'obbedienza a una richiesta."),
  flag("se ci tenessi a me", "Ricatto emotivo", "high", "Usa il legame affettivo come leva per ottenere qualcosa."),
  flag("dopo tutto quello che ho fatto per te", "Senso di colpa", "high", "Trasforma gesti passati in un debito da riscuotere."),
  flag("mi devi questo", "Senso di colpa", "medium", "Presenta una scelta personale come obbligo verso l'altro."),
  flag("sei un ingrato", "Senso di colpa", "high", "Attacca il carattere per ottenere conformità o silenzio."),
  flag("mi fai stare male", "Senso di colpa", "medium", "Attribuisce interamente a te la gestione delle emozioni altrui."),
  flag("mi hai costretto tu", "Scarico di responsabilità", "high", "Nega la propria scelta e ne attribuisce la colpa a te."),
  flag("è colpa tua se reagisco così", "Scarico di responsabilità", "high", "Giustifica un comportamento dannoso come conseguenza inevitabile."),
  flag("guarda cosa mi hai fatto fare", "Scarico di responsabilità", "high", "Trasferisce la responsabilità di un'azione su chi la subisce."),
  flag("me la sono cercata", "Colpevolizzazione", "high", "Attribuisce alla vittima la responsabilità del danno ricevuto."),
  flag("te la sei cercata", "Colpevolizzazione", "high", "Giustifica il danno accusando chi lo ha subito."),
  flag("se non mi provocassi", "Scarico di responsabilità", "high", "Presenta l'autocontrollo dell'altro come tua responsabilità."),
  flag("sei tu che mi fai arrabbiare", "Scarico di responsabilità", "medium", "Nega la responsabilità personale nella gestione della rabbia."),
  flag("io sono fatto così", "Evitamento", "medium", "Usa l'identità come scusa per non cambiare un comportamento lesivo."),
  flag("non posso farci niente", "Evitamento", "low", "Dichiara impotenza per sottrarsi a responsabilità e cambiamento."),
  flag("non cambierò mai", "Evitamento", "medium", "Chiude la possibilità di negoziare comportamenti più rispettosi."),
  flag("prendere o lasciare", "Ultimatum", "high", "Elimina lo spazio di dialogo imponendo un'alternativa rigida."),
  flag("o fai come dico io o niente", "Controllo", "high", "Impone obbedienza e cancella la negoziazione."),
  flag("non hai scelta", "Controllo", "high", "Nega la tua autonomia decisionale."),
  flag("decido io", "Controllo", "high", "Rivendica unilateralmente il potere decisionale."),
  flag("devi chiedermi il permesso", "Controllo", "high", "Subordina la tua autonomia all'approvazione dell'altro."),
  flag("non puoi uscire", "Controllo", "high", "Limita la libertà personale con un divieto diretto."),
  flag("non voglio che tu lo veda", "Controllo", "medium", "Può tentare di controllare relazioni e contatti personali."),
  flag("vestiti in modo diverso", "Controllo", "medium", "Impone preferenze sul tuo corpo o sulla tua espressione."),
  flag("dammi il telefono", "Controllo", "high", "Pretende accesso a uno spazio personale e riservato."),
  flag("se non hai niente da nascondere", "Controllo", "high", "Usa il sospetto per forzare la rinuncia alla privacy."),
  flag("voglio sapere sempre dove sei", "Controllo", "high", "Normalizza un monitoraggio costante degli spostamenti."),
  flag("mandami la posizione", "Controllo", "medium", "Può imporre tracciamento senza un consenso libero e reciproco."),
  flag("con chi stavi parlando", "Controllo", "low", "Nel contesto sbagliato può essere una richiesta di rendicontazione."),
  flag("non mi fido dei tuoi amici", "Isolamento", "medium", "Può servire a screditare sistematicamente la rete sociale."),
  flag("sei mio", "Possesso", "high", "Descrive una persona come proprietà anziché come soggetto autonomo."),
  flag("sei mia", "Possesso", "high", "Descrive una persona come proprietà anziché come soggetto autonomo."),
  flag("senza di me non sei niente", "Svalutazione", "high", "Mira a ridurre autostima e indipendenza."),
  flag("senza di me non ce la faresti", "Dipendenza", "high", "Insinua incapacità per aumentare la dipendenza dall'altro."),
  flag("non sei capace", "Svalutazione", "high", "Attacca la competenza in modo assoluto."),
  flag("non combini mai niente", "Svalutazione", "high", "Generalizza un giudizio negativo sull'intera persona."),
  flag("sbagli sempre tutto", "Generalizzazione", "high", "Usa un assoluto per cancellare sfumature e risultati positivi."),
  flag("fai sempre così", "Generalizzazione", "medium", "Trasforma un episodio in un tratto permanente."),
  flag("non fai mai niente per me", "Generalizzazione", "medium", "Cancella ogni contributo usando un assoluto accusatorio."),
  flag("sei sempre il solito", "Generalizzazione", "medium", "Blocca la persona in un'etichetta negativa stabile."),
  flag("non cambierai mai", "Svalutazione", "high", "Nega la possibilità di crescita e può alimentare impotenza."),
  flag("chi vuoi che ti voglia", "Svalutazione", "high", "Colpisce il valore personale e la paura dell'abbandono."),
  flag("sei fortunato che sto con te", "Svalutazione", "high", "Crea una gerarchia affettiva e riduce l'autostima."),
  flag("sei fortunata che sto con te", "Svalutazione", "high", "Crea una gerarchia affettiva e riduce l'autostima."),
  flag("non troverai nessuno come me", "Dipendenza", "high", "Usa la paura del futuro per trattenerti."),
  flag("nessun altro ti vorrà", "Intimidazione", "high", "Minaccia isolamento affettivo per ridurre la libertà di scelta."),
  flag("se te ne vai te ne pentirai", "Minaccia", "high", "Associa l'uscita dalla relazione a conseguenze intimidatorie."),
  flag("se mi lasci mi ammazzo", "Ricatto emotivo", "high", "Usa una minaccia di autolesionismo per impedire una scelta libera; serve supporto immediato."),
  flag("è meglio che fai attenzione", "Minaccia", "high", "Suggerisce conseguenze senza dichiararle apertamente."),
  flag("non sai di cosa sono capace", "Minaccia", "high", "Evoca una possibile ritorsione per generare paura."),
  flag("te la farò pagare", "Minaccia", "high", "Promette una ritorsione diretta."),
  flag("non finisce qui", "Minaccia", "medium", "Può implicare una futura ritorsione o escalation."),
  flag("vedrai cosa succede", "Minaccia", "medium", "Mantiene vaga una conseguenza per aumentare l'ansia."),
  flag("sto solo cercando di aiutarti", "Falsa premura", "low", "Può mascherare controllo o critica come aiuto non richiesto."),
  flag("lo faccio per il tuo bene", "Falsa premura", "medium", "Giustifica un'imposizione dichiarando un beneficio per te."),
  flag("un giorno mi ringrazierai", "Falsa premura", "medium", "Presume di sapere meglio di te cosa ti serve."),
  flag("fidati di me e basta", "Pressione", "medium", "Chiede fiducia cieca e scoraggia domande legittime."),
  flag("non fare domande", "Controllo", "high", "Impedisce di cercare informazioni o chiarimenti."),
  flag("non complicare le cose", "Silenziamento", "medium", "Scoraggia il confronto presentandolo come un problema inutile."),
  flag("lascia perdere", "Silenziamento", "low", "Può chiudere una questione senza ascolto o soluzione."),
  flag("non ne voglio parlare", "Evitamento", "low", "Se ricorrente, blocca ogni possibilità di affrontare il problema."),
  flag("è inutile parlarne", "Evitamento", "medium", "Dichiara il dialogo inutile prima che possa avvenire."),
  flag("finché vivi sotto questo tetto", "Controllo", "high", "Usa casa o sostegno materiale come leva di obbedienza."),
  flag("sono io che pago", "Controllo economico", "high", "Usa il denaro per rivendicare potere decisionale totale."),
  flag("non hai bisogno di lavorare", "Controllo economico", "medium", "Può scoraggiare l'autonomia economica e aumentare la dipendenza."),
  flag("i soldi li gestisco io", "Controllo economico", "high", "Esclude unilateralmente l'altra persona dalle decisioni finanziarie."),
  flag("dimmi quanto hai speso", "Controllo economico", "medium", "Può diventare sorveglianza finanziaria se non è reciproco e concordato."),
  flag("mi metti in imbarazzo", "Vergogna", "medium", "Usa la vergogna per controllare espressione o comportamento."),
  flag("che figura mi fai fare", "Vergogna", "medium", "Sposta l'attenzione sulla reputazione per imporre conformità."),
  flag("cosa penserà la gente", "Pressione sociale", "low", "Invoca il giudizio esterno per limitare una scelta personale."),
  flag("una persona normale non farebbe così", "Normalizzazione", "high", "Definisce la normalità per patologizzare una scelta diversa."),
  flag("sei l'unico che la pensa così", "Pressione sociale", "medium", "Isola la tua opinione presentandola come anomala."),
  flag("cresci", "Svalutazione", "medium", "Riduce una posizione a immaturità senza discuterla."),
  flag("comportati da adulto", "Svalutazione", "medium", "Usa un giudizio di maturità per chiudere il confronto."),
  flag("smettila di fare la vittima", "Colpevolizzazione", "high", "Scredita la segnalazione di un danno come strategia opportunistica."),
  flag("vuoi solo attirare l'attenzione", "Svalutazione", "high", "Attribuisce un secondo fine per invalidare una richiesta d'aiuto."),
  flag("sei egoista", "Senso di colpa", "medium", "Può trasformare un confine personale in una colpa morale."),
  flag("pensi solo a te", "Senso di colpa", "medium", "Generalizza per colpevolizzare una scelta o un limite."),
  flag("non fare l'egoista", "Pressione", "medium", "Usa un'etichetta morale per ottenere assenso."),
  flag("se fossi una brava persona", "Ricatto morale", "high", "Condiziona il valore morale all'obbedienza."),
  flag("una brava compagna lo farebbe", "Ruoli imposti", "high", "Impone un ruolo affettivo per ottenere conformità."),
  flag("un vero uomo non piange", "Ruoli imposti", "high", "Usa uno stereotipo di genere per reprimere emozioni."),
  flag("una vera donna dovrebbe", "Ruoli imposti", "high", "Usa uno stereotipo di genere per imporre comportamento."),
  flag("non essere debole", "Vergogna", "medium", "Presenta vulnerabilità o richiesta d'aiuto come difetto."),
  flag("ti perdono anche se", "Superiorità morale", "low", "Può creare una posizione morale superiore senza responsabilità reciproca."),
  flag("io non sbaglio mai", "Superiorità morale", "medium", "Rende impossibile un confronto paritario sulla responsabilità."),
  flag("sei tu il problema", "Colpevolizzazione", "high", "Riduce una dinamica complessa a un difetto personale."),
  flag("il problema sei tu", "Colpevolizzazione", "high", "Assegna tutta la responsabilità alla persona, non ai comportamenti."),
  flag("con te non si può parlare", "Silenziamento", "medium", "Chiude il dialogo attribuendone il fallimento interamente a te."),
  flag("non meriti spiegazioni", "Punizione", "high", "Nega deliberatamente informazioni come forma di potere."),
  flag("ti ignorerò finché non capisci", "Punizione", "high", "Usa il silenzio come punizione e strumento di controllo."),
  flag("non ti parlo più", "Punizione", "medium", "Può minacciare ritiro affettivo per ottenere obbedienza."),
  flag("fai come vuoi", "Passivo-aggressività", "low", "Nel contesto può esprimere disapprovazione punitiva invece di consenso."),
  flag("contento tu", "Passivo-aggressività", "low", "Può svalutare una scelta evitando un confronto diretto."),
  flag("bravo, complimenti", "Sarcasmo", "low", "Detto sarcasticamente, usa la derisione al posto del dialogo."),
  flag("era ovvio", "Svalutazione", "low", "Fa apparire una difficoltà come prova di incapacità."),
  flag("dovresti già saperlo", "Svalutazione", "medium", "Usa aspettative implicite per generare vergogna."),
  flag("non sei all'altezza", "Svalutazione", "high", "Formula un giudizio globale di inadeguatezza."),
  flag("mi deludi", "Senso di colpa", "medium", "Può trasformare una scelta autonoma in fallimento affettivo."),
  flag("non me lo aspettavo da te", "Senso di colpa", "medium", "Usa aspettative personali per indurre vergogna o conformità."),
  flag("se continui così ti lascio", "Ultimatum", "high", "Usa la minaccia di abbandono per controllare il comportamento."),
  flag("posso sostituirti quando voglio", "Intimidazione", "high", "Minaccia sostituzione per creare insicurezza e obbedienza."),
  flag("non vali niente", "Svalutazione", "high", "Attacco diretto al valore personale."),
];

const expandedRedFlags: RedFlag[] = [
  ...group([
    "non capisci niente", "non hai capito proprio nulla", "è troppo difficile per te", "non ci arrivi proprio",
    "devo spiegarti anche le cose più semplici", "non sai nemmeno questo", "sei proprio ignorante", "parli senza sapere",
    "non sai di cosa stai parlando", "prima studia e poi parla", "informati prima di aprire bocca", "ti manca proprio la cultura",
    "non hai gli strumenti per capire", "non sei abbastanza intelligente", "non è un discorso alla tua portata", "lascia parlare chi ne capisce",
    "questa cosa è oltre le tue capacità", "hai una comprensione molto limitata", "non riesci a seguire un ragionamento semplice",
    "con te bisogna partire dall'abc", "non distingui nemmeno le basi", "non hai alcuna competenza", "la tua opinione non vale perché non sai nulla",
    "ti fai confondere da qualsiasi cosa", "sei lento a capire", "non sai ragionare", "non hai senso critico", "credi a tutto quello che senti",
    "non sei in grado di valutare", "non hai la preparazione necessaria", "questa conversazione è troppo avanzata per te",
  ], "Inferiorizzazione intellettuale", "high", "Attacca intelligenza o cultura per creare inferiorità e togliere valore alla posizione espressa."),

  ...group([
    "che domanda stupida", "ma ti senti quando parli", "hai detto davvero questa cosa", "questa è la cosa più assurda che abbia mai sentito",
    "fai ridere quando provi a spiegarti", "non riesco a prenderti sul serio", "sei una barzelletta", "ti rendi ridicolo da solo",
    "che figuraccia", "continua pure a renderti ridicolo", "tutti stanno ridendo di te", "ma guardati",
    "sembri un bambino", "parli come un bambino", "hai una logica da asilo", "che tenero quando provi a ragionare",
    "vuoi anche un applauso", "complimenti per la brillante idea", "questa me la devo segnare per farmi due risate", "non sai quanto sei comico",
    "è imbarazzante ascoltarti", "ti stai coprendo di ridicolo", "non hai proprio dignità", "fai pena quando insisti",
    "è quasi divertente vederti provare", "non sai nemmeno difenderti", "sei la caricatura di te stesso", "che spettacolo pietoso",
    "non farmi ridere", "smettila che fai solo brutte figure", "ti manca solo il naso rosso", "questa era la tua argomentazione",
  ], "Ridicolizzazione", "high", "Usa derisione e umiliazione per spostare l'attenzione dall'argomento al valore della persona."),

  ...group([
    "fammi finire e poi forse puoi parlare", "non interrompermi mentre ti sto spiegando", "adesso parlo io", "il tuo turno è finito",
    "non ti ho dato la parola", "stai zitto e ascolta", "stai zitta e ascolta", "chiudi la bocca", "basta parlare",
    "non voglio sentire altro", "la discussione finisce qui", "non c'è più niente da dire", "non meriti una risposta",
    "non perdo tempo a risponderti", "non vale la pena ascoltarti", "la tua opinione non è richiesta", "nessuno ti ha chiesto niente",
    "non cambiare discorso", "smettila di contestare tutto", "non discutere ogni cosa", "non fare obiezioni",
    "lascia perdere le tue spiegazioni", "non giustificarti", "non iniziare con le tue storie", "risparmiami il tuo punto di vista",
    "non parlare sopra di me", "ascolta senza replicare", "non devi avere sempre l'ultima parola", "ti dirò io quando puoi rispondere",
    "questa non è una conversazione", "non c'è niente da discutere", "il discorso è chiuso", "non intendo ascoltare altre scuse",
  ], "Interruzione e silenziamento", "high", "Impedisce il dialogo o controlla chi può parlare, riducendo la possibilità di esprimersi e dissentire."),

  ...group([
    "io ne so molto più di te", "io ho molta più esperienza", "fidati che ne capisco più io", "non puoi competere con me",
    "io sono su un altro livello", "tu non sei al mio livello", "io sono sempre un passo avanti", "senza di me sareste persi",
    "sono io quello competente", "sono io quella competente", "qui l'unico che ragiona sono io", "qui l'unica che ragiona sono io",
    "se funziona è grazie a me", "ho dovuto sistemare tutto io", "come sempre devo salvare la situazione", "nessuno lo fa bene quanto me",
    "io non ho bisogno di consigli", "non ho nulla da imparare da te", "tu dovresti imparare da me", "dovresti essere grato di avermi vicino",
    "io vedo cose che tu non puoi vedere", "sono troppo avanti per farmi capire", "le persone intelligenti mi capiscono", "io ottengo sempre quello che voglio",
    "sono abituato a persone di un altro livello", "sono abituata a persone di un altro livello", "io non mi abbasso a certe discussioni",
    "parlare con te è una perdita di talento", "il mio tempo vale più del tuo", "io porto valore tu porti problemi", "tutti dipendono da me",
    "sono indispensabile", "senza il mio contributo non esisterebbe nulla", "io sono quello che tiene tutto insieme",
  ], "Superiorità e autoesaltazione", "medium", "Costruisce una gerarchia proclamando superiorità, indispensabilità o diritto speciale per ridurre l'altro."),

  ...group([
    "stai confondendo i fatti", "la tua versione non ha senso", "ti sei costruito una storia", "ti sei costruita una storia",
    "vedi problemi dove non ce ne sono", "interpreti tutto male", "hai una percezione alterata", "non sei lucido",
    "non sei lucida", "non puoi fidarti del tuo giudizio", "devi fidarti della mia memoria", "so meglio io cosa è successo",
    "hai cambiato completamente la storia", "stai riscrivendo quello che è successo", "nessuno ha visto quello che dici tu",
    "sei l'unico a ricordarla così", "sei l'unica a ricordarla così", "hai una memoria selettiva", "confondi i sogni con la realtà",
    "stai creando un problema dal nulla", "ti inventi intenzioni che non esistono", "hai bisogno di farti controllare", "non sei stabile",
    "non sei affidabile quando racconti le cose", "le tue emozioni ti impediscono di capire", "quando sei così non ragioni",
    "stai perdendo il contatto con la realtà", "non puoi sapere davvero cosa hai sentito", "ti convinci di cose mai successe",
    "la tua testa ti gioca brutti scherzi", "sei troppo confuso per ricordare", "sei troppo confusa per ricordare",
    "io non ho fatto nulla di ciò che dici", "questa è soltanto la tua fantasia", "hai sempre avuto problemi a distinguere i fatti",
  ], "Gaslighting e realtà", "high", "Mette sistematicamente in dubbio memoria, percezione o lucidità per imporre una versione dominante dei fatti."),

  ...group([
    "se dici di no vuol dire che non ti importa", "se mi volessi bene non esiteresti", "una persona che ama non mette limiti",
    "mi spezzi il cuore ogni volta", "mi stai abbandonando nel momento peggiore", "sei responsabile della mia felicità",
    "senza il tuo sì starò malissimo", "non puoi farmi questo", "non dopo tutto quello che abbiamo passato", "mi stai tradendo",
    "stai distruggendo la nostra famiglia", "vuoi davvero farmi soffrire", "se rifiuti non potrò perdonarti", "dimostrami che ci tieni",
    "fai questo piccolo sacrificio per me", "io lo farei senza pensarci per te", "evidentemente io tengo più a te",
    "mi aspettavo che scegliessi me", "se scegli te stesso mi perdi", "se scegli te stessa mi perdi", "non posso credere che tu sia così freddo",
    "non posso credere che tu sia così fredda", "mi fai sentire come se non contassi nulla", "dopo questo non so più chi sei",
    "mi hai rovinato la giornata", "sarà colpa tua se starò male", "non dormirò per colpa tua", "ricorderò sempre che mi hai detto di no",
    "questa cosa dimostra quanto poco mi ami", "se te ne importasse faresti uno sforzo", "non chiederei se non fosse importante",
    "mi devi almeno una possibilità", "non puoi negarmi anche questo", "sei l'unica persona che può salvarmi",
  ], "Ricatto emotivo e colpa", "high", "Trasforma affetto, sofferenza o debito emotivo in una leva per ottenere consenso e superare i confini."),

  ...group([
    "fai esattamente quello che ti dico", "non prendere decisioni senza di me", "prima ne parli con me", "devo approvare ogni scelta",
    "non puoi decidere da solo", "non puoi decidere da sola", "io so cosa è meglio per te", "lascia che decida chi ne sa di più",
    "non andare da nessuna parte senza avvisarmi", "devi rispondermi subito", "voglio le password", "non bloccare mai il telefono",
    "fammi vedere i messaggi", "chiama davanti a me", "metti il vivavoce", "non cancellare la cronologia",
    "non accetto che tu abbia segreti", "non puoi avere spazi privati", "devo conoscere ogni persona che frequenti", "non uscire con loro",
    "non parlare con quella persona", "non pubblicare quella foto", "togliti quella cosa", "non vestirti così quando non ci sono",
    "non spendere senza chiedere", "dammi accesso al tuo conto", "lo stipendio lo gestisco io", "non ti serve un conto tuo",
    "non firmare nulla senza di me", "non accettare quel lavoro", "non studiare quella cosa", "non partire senza il mio consenso",
    "devi fare come abbiamo stabilito io", "le regole le faccio io", "in questa casa comando io",
  ], "Controllo coercitivo", "high", "Limita autonomia, privacy, relazioni o risorse imponendo sorveglianza, permessi e obbedienza."),

  ...group([
    "quelle persone ti usano", "i tuoi amici non ti vogliono davvero bene", "la tua famiglia non ti capisce", "ti riempiono la testa di bugie",
    "da quando li frequenti sei cambiato", "da quando li frequenti sei cambiata", "scegli loro invece di me", "se vai da loro non tornare",
    "non voglio quella persona in casa", "i tuoi colleghi ridono di te", "nessuno al lavoro ti rispetta", "sono l'unico dalla tua parte",
    "sono l'unica dalla tua parte", "gli altri vogliono separarci", "non parlare dei nostri problemi fuori", "uno psicologo ti metterebbe contro di me",
    "non hai bisogno di uno psicologo", "non coinvolgere la tua famiglia", "non chiamare i tuoi amici", "non chiedere consiglio a nessuno",
    "le persone single sono gelose di noi", "chi ti consiglia di lasciarmi ti invidia", "tutti cercano di manipolarti tranne me",
    "solo con me puoi essere te stesso", "solo con me puoi essere te stessa", "fuori da qui nessuno ti accetterebbe",
    "gli altri vedono solo il peggio di te", "ti proteggo io dal mondo", "non fidarti di nessuno oltre a me", "non raccontare questa cosa al medico",
    "non andare a quell'appuntamento", "cancella quel contatto", "blocca quella persona", "la tua rete di supporto è il vero problema",
  ], "Isolamento sociale", "high", "Scredita o limita la rete di supporto per aumentare dipendenza, segretezza e vulnerabilità."),

  ...group([
    "è evidente a chiunque", "qualsiasi persona ragionevole sarebbe d'accordo", "solo tu non lo capisci", "nessuno sano di mente la pensa così",
    "i fatti parlano da soli", "non c'è bisogno di dimostrarlo", "è risaputo che ho ragione", "non puoi negare l'evidenza",
    "se non sei d'accordo sei in malafede", "chi mi critica è solo geloso", "chiunque mi conosca sa come stanno le cose",
    "non serve ascoltare anche l'altra versione", "la verità è una sola ed è la mia", "non esistono alternative sensate",
    "se fossi obiettivo mi daresti ragione", "se fossi obiettiva mi daresti ragione", "il tuo disaccordo dimostra che non hai capito",
    "se mi contraddici confermi quello che dico", "il fatto che ti difendi dimostra che sei colpevole", "se non rispondi vuol dire che ho ragione",
    "qualunque risposta darai sarà una scusa", "non puoi vincere questa discussione", "ho già dimostrato tutto", "non c'è spazio per opinioni",
    "questa non è un'opinione è un fatto", "non devo portarti prove", "spetta a te dimostrare che sbaglio", "la maggioranza non può sbagliare",
    "le persone intelligenti concordano con me", "solo chi ha qualcosa da nascondere si oppone", "il tuo tono dimostra che ho ragione",
    "se ti arrabbi è perché ho colpito nel segno", "se piangi è perché sai che è vero", "la tua reazione è la mia prova",
  ], "Falsa logica e consenso", "medium", "Presenta opinioni come fatti inevitabili o usa la reazione dell'altro come prova, rendendo impossibile dissentire."),

  ...group([
    "ricordati che posso renderti la vita difficile", "so come colpirti", "conosco tutti i tuoi punti deboli", "non sfidarmi",
    "non mettermi alla prova", "non costringermi a diventare cattivo", "non costringermi a diventare cattiva", "potrei raccontare tutto",
    "so cose che non vuoi far sapere", "posso rovinare la tua reputazione", "posso farti perdere il lavoro", "posso portarti via tutto",
    "nessuno verrà ad aiutarti", "farai meglio a obbedire", "questa è la tua ultima possibilità", "scegli bene cosa dire adesso",
    "se parli ci saranno conseguenze", "non sai in che guaio ti stai mettendo", "posso arrivare ovunque tu vada", "non riuscirai a liberarti di me",
    "ti terrò d'occhio", "so dove trovarti", "non pensare di essere al sicuro", "te ne farò pentire amaramente",
    "pagheranno anche le persone a cui tieni", "non provocare una reazione che non puoi gestire", "poi non dire che non ti avevo avvertito",
    "hai ancora tempo per rimediare", "questa volta lascio correre", "la prossima volta sarà peggio", "non farmi perdere la pazienza",
    "sai cosa succede quando mi arrabbio", "non rispondo più di me", "potrei perdere il controllo",
  ], "Minaccia e intimidazione", "high", "Evoca danni, ritorsioni o perdita di controllo per generare paura e ottenere obbedienza."),

  ...group([
    "certo come no", "sì va bene campione", "sì va bene campionessa", "che grande esperto", "che grande esperta",
    "meno male che ci sei tu", "ora sì che hai risolto tutto", "geniale davvero", "sei proprio un fenomeno", "applausi",
    "vuoi una medaglia", "bravissimo come sempre", "bravissima come sempre", "non avevo dubbi che avresti sbagliato", "sorprendente che tu ci sia riuscito",
    "sorprendente che tu ci sia riuscita", "per una volta ne hai fatta una giusta", "non montarti la testa", "non credere di essere diventato bravo",
    "non credere di essere diventata brava", "forse un giorno capirai", "quando sarai grande ne riparliamo", "te lo spiegherei ma sarebbe inutile",
    "non spreco parole con te", "che dolce la tua ingenuità", "beata ignoranza", "continua a vivere nel tuo mondo", "sei adorabile quando sei convinto",
    "sei adorabile quando sei convinta", "la tua sicurezza è quasi commovente", "va bene professore", "va bene professoressa", "come dici tu genio",
    "complimenti hai scoperto l'acqua calda",
  ], "Sarcasmo e disprezzo", "medium", "Usa ironia e falso elogio per umiliare, sminuire competenza o evitare una risposta diretta."),

  ...group([
    "non sei tagliato per questo lavoro", "non sei tagliata per questo lavoro", "qui sei facilmente sostituibile", "ci sono cento persone migliori di te",
    "dovresti ringraziarmi per questa opportunità", "senza la mia raccomandazione non saresti qui", "il tuo posto dipende da me",
    "non fare carriera contro di me", "posso bloccare la tua crescita", "decido io chi viene ascoltato", "non portare idee senza passare da me",
    "questa idea diventa mia", "lascia che la presenti io", "tu non sapresti venderla", "non sei pronto per avere visibilità",
    "non sei pronta per avere visibilità", "non parlare in riunione se non te lo chiedo", "non contraddirmi davanti agli altri", "sorridi e non creare problemi",
    "segnalerò che non sei collaborativo", "segnalerò che non sei collaborativa", "chi si lamenta non dura qui", "qui bisogna saper incassare",
    "non sei abbastanza resiliente", "questo ambiente è per persone forti", "gli straordinari dimostrano lealtà", "se ci tenessi al progetto resteresti",
    "la tua vita privata non è un mio problema", "tutti fanno sacrifici tranne te", "non aspettarti riconoscimenti", "dovresti accontentarti di avere un lavoro",
    "il merito non basta devi compiacermi", "la tua valutazione la decido io", "posso rendere invisibile il tuo contributo", "nessuno noterà se te ne vai",
  ], "Manipolazione sul lavoro", "high", "Usa potere, precarietà, visibilità o carriera per imporre silenzio, appropriazione del merito e disponibilità non libera."),

  ...group([
    "sei troppo brutto per pretendere di più", "sei troppo brutta per pretendere di più", "dovresti ringraziare chi ti guarda", "non sei più attraente come prima",
    "con quel corpo non puoi permettertelo", "chi vuoi impressionare vestito così", "senza trucco sei irriconoscibile", "con il trucco sembri finta",
    "sei ingrassato e si vede", "sei ingrassata e si vede", "sei troppo magro per piacere", "sei troppo magra per piacere",
    "alla tua età dovresti coprirti", "non hai più l'età per vestirti così", "nessuno vuole vedere il tuo corpo", "io ti accetto nonostante il tuo aspetto",
    "potresti essere bello se mi ascoltassi", "potresti essere bella se mi ascoltassi", "gli altri ti giudicano per come appari", "mi fai fare brutta figura vestito così",
    "mi fai fare brutta figura vestita così", "non sei il tipo che viene notato", "non illuderti per un complimento", "sei carino ma non abbastanza",
    "sei carina ma non abbastanza", "dovresti sistemarti prima di uscire", "sembri trascurato", "sembri trascurata", "il tuo aspetto parla male di me",
    "non troverai qualcuno che accetti i tuoi difetti", "io sono fuori dalla tua portata", "tu non sei fuori dalla mia portata",
  ], "Vergogna sul corpo", "high", "Colpisce aspetto, età o corpo per creare vergogna, dipendenza e controllo sull'espressione personale."),

  ...group([
    "sei troppo emotivo per decidere", "sei troppo emotiva per decidere", "quando piangi perdi credibilità", "la tua ansia rende tutto inaffidabile",
    "usi le emozioni per manipolare", "fai apposta a stare male", "la tua tristezza rovina tutto", "nessuno ha tempo per i tuoi problemi",
    "sei pesante da sopportare", "devi smetterla di sentirti così", "non hai motivi per essere triste", "c'è chi sta peggio quindi taci",
    "la tua paura è assurda", "sei debole perché chiedi aiuto", "vai in terapia perché sei rotto", "vai in terapia perché sei rotta",
    "solo una persona instabile reagirebbe così", "non posso fidarmi di chi ha questi problemi", "la tua diagnosi è solo una scusa",
    "prendi i farmaci e smettila", "sei malato di mente", "sei malata di mente", "le tue emozioni non contano come fatti",
    "se fossi più forte non avresti bisogno di aiuto", "ti piace stare male", "cerchi compassione", "vuoi che tutti si occupino di te",
    "sei dipendente dall'attenzione", "non puoi prendere decisioni quando sei così", "devo proteggerti da te stesso", "devo proteggerti da te stessa",
    "non sei capace di gestire la tua vita", "il tuo terapeuta non ti conosce come me", "io so cosa è meglio per la tua salute mentale",
  ], "Stigma emotivo e psicologico", "high", "Usa emozioni, vulnerabilità o salute mentale per togliere credibilità, autonomia e diritto al supporto."),
];

export const redFlags: RedFlag[] = Array.from(
  new Map([...baseRedFlags, ...expandedRedFlags].map((entry) => [entry.phrase.toLocaleLowerCase("it"), entry])).values(),
);

export const severityLabels: Record<Severity, string> = {
  high: "Alta",
  medium: "Media",
  low: "Bassa",
};
