import type { RedFlag, Severity } from "./redFlags";

const flag = (
  phrase: string,
  category: string,
  severity: Severity,
  explanation: string,
): RedFlag => ({ phrase, category, severity, explanation });

const group = (
  phrases: string[],
  category: string,
  severity: Severity,
  explanation: string,
): RedFlag[] => phrases.map((phrase) => flag(phrase, category, severity, explanation));

const baseRedFlagsEn: RedFlag[] = [
  flag("you're too sensitive", "Invalidation", "high", "Dismisses an emotional response instead of addressing its cause."),
  flag("you are too sensitive", "Invalidation", "high", "Dismisses an emotional response instead of addressing its cause."),
  flag("you're overreacting", "Invalidation", "medium", "Minimises the legitimacy of what you feel or describe."),
  flag("you are overreacting", "Invalidation", "medium", "Minimises the legitimacy of what you feel or describe."),
  flag("you're being dramatic", "Invalidation", "high", "Labels emotion as performance to avoid engaging with it."),
  flag("stop being dramatic", "Invalidation", "high", "Frames genuine distress as theatre rather than listening."),
  flag("it's not a big deal", "Minimisation", "medium", "Reduces the importance of an issue without considering its impact."),
  flag("it was just a joke", "Minimisation", "medium", "Uses intent to dismiss the impact of hurtful words."),
  flag("can't you take a joke", "Invalidation", "medium", "Blames your reaction instead of addressing the hurtful comment."),
  flag("calm down", "Invalidation", "low", "Can dismiss the emotion instead of responding to its content."),
  flag("just relax", "Invalidation", "low", "Can brush aside a concern without addressing its source."),
  flag("get over it", "Invalidation", "medium", "Demands that distress disappear without care or resolution."),
  flag("you're crazy", "Gaslighting", "high", "Attacks your sanity to discredit your account."),
  flag("you are crazy", "Gaslighting", "high", "Attacks your sanity to discredit your account."),
  flag("you're paranoid", "Gaslighting", "high", "Labels a concern as irrational to avoid answering it."),
  flag("you imagined it", "Gaslighting", "high", "Presents your perception as something invented."),
  flag("it's all in your head", "Gaslighting", "high", "Denies the reality of your experience or distress."),
  flag("that never happened", "Gaslighting", "high", "Directly denies an event you remember."),
  flag("I never said that", "Gaslighting", "medium", "May deny earlier words and destabilise the shared account."),
  flag("you're remembering it wrong", "Gaslighting", "medium", "Calls your memory unreliable without discussing evidence."),
  flag("you misunderstood me", "Gaslighting", "medium", "Automatically places responsibility on your understanding."),
  flag("you're twisting everything", "Gaslighting", "medium", "Discredits your version without clarifying the facts."),
  flag("you're making things up", "Gaslighting", "high", "Accuses you of inventing experiences rather than engaging with them."),
  flag("no one will believe you", "Intimidation", "high", "Uses fear of disbelief to isolate and silence you."),
  flag("everyone agrees with me", "Social pressure", "medium", "Uses an alleged majority instead of discussing the issue."),
  flag("everyone thinks you're", "Social pressure", "high", "Invokes unverifiable group judgement to undermine you."),
  flag("everyone says so", "Social pressure", "medium", "Uses an undefined group as authority against you."),
  flag("no one likes you", "Isolation", "high", "Targets belonging and can increase dependence on the speaker."),
  flag("no one can stand you", "Isolation", "high", "Attacks your sense of social support and belonging."),
  flag("I'm the only one who understands you", "Isolation", "high", "Claims exclusive understanding to create dependence."),
  flag("your friends are against us", "Isolation", "high", "Discredits your support network and encourages isolation."),
  flag("your family is toxic", "Isolation", "medium", "May be used to sever support without discussing specific behaviour."),
  flag("don't tell anyone", "Secrecy", "high", "Imposes secrecy and reduces opportunities to seek support."),
  flag("this stays between us", "Secrecy", "medium", "Pressures you to conceal potentially harmful behaviour."),
  flag("if you really loved me", "Emotional blackmail", "high", "Makes love conditional on complying with a demand."),
  flag("if you cared about me", "Emotional blackmail", "high", "Uses the relationship as leverage to obtain compliance."),
  flag("after everything I've done for you", "Guilt", "high", "Turns past care into a debt that must be repaid."),
  flag("you owe me", "Guilt", "medium", "Presents a personal choice as an obligation to the speaker."),
  flag("you're ungrateful", "Guilt", "high", "Attacks character to produce compliance or silence."),
  flag("you make me feel terrible", "Guilt", "medium", "Makes you solely responsible for another person's emotions."),
  flag("you made me do it", "Blame shifting", "high", "Denies personal choice and transfers responsibility to you."),
  flag("look what you made me do", "Blame shifting", "high", "Blames the recipient for the speaker's harmful action."),
  flag("it's your fault I react this way", "Blame shifting", "high", "Frames harmful behaviour as your unavoidable consequence."),
  flag("you asked for it", "Victim blaming", "high", "Assigns responsibility for harm to the person who received it."),
  flag("you brought this on yourself", "Victim blaming", "high", "Justifies harm by blaming the person affected."),
  flag("if you didn't provoke me", "Blame shifting", "high", "Makes the other person's self-control your responsibility."),
  flag("you make me angry", "Blame shifting", "medium", "Denies personal responsibility for managing anger."),
  flag("that's just who I am", "Avoidance", "medium", "Uses identity as a reason not to change harmful behaviour."),
  flag("I can't help it", "Avoidance", "low", "Claims helplessness to avoid responsibility and change."),
  flag("I'll never change", "Avoidance", "medium", "Closes down negotiation about more respectful behaviour."),
  flag("take it or leave it", "Ultimatum", "high", "Removes space for dialogue by imposing a rigid choice."),
  flag("my way or the highway", "Control", "high", "Demands obedience and eliminates negotiation."),
  flag("you have no choice", "Control", "high", "Denies your decision-making autonomy."),
  flag("I make the decisions", "Control", "high", "Claims unilateral authority over shared or personal choices."),
  flag("you need my permission", "Control", "high", "Makes your autonomy dependent on another person's approval."),
  flag("you're not allowed to go out", "Control", "high", "Directly restricts personal freedom."),
  flag("I don't want you seeing them", "Control", "medium", "Attempts to control personal relationships and contact."),
  flag("change your clothes", "Control", "medium", "Imposes preferences on your body or self-expression."),
  flag("give me your phone", "Control", "high", "Demands access to a private personal space."),
  flag("if you have nothing to hide", "Control", "high", "Uses suspicion to force you to surrender privacy."),
  flag("I need to know where you are at all times", "Control", "high", "Normalises constant monitoring of your location."),
  flag("send me your location", "Control", "medium", "May impose tracking without free and mutual consent."),
  flag("who were you talking to", "Control", "low", "In context, this can become a demand for constant accounting."),
  flag("I don't trust your friends", "Isolation", "medium", "May systematically discredit your social support network."),
  flag("you belong to me", "Possession", "high", "Describes a person as property rather than autonomous."),
  flag("you're mine", "Possession", "high", "Frames the relationship as ownership rather than consent."),
  flag("without me you're nothing", "Devaluation", "high", "Targets self-worth and independence."),
  flag("you couldn't manage without me", "Dependency", "high", "Suggests incapability to increase dependence."),
  flag("you're incapable", "Devaluation", "high", "Makes a sweeping attack on competence."),
  flag("you never get anything right", "Devaluation", "high", "Uses an absolute judgement to erase competence and progress."),
  flag("you always ruin everything", "Generalisation", "high", "Uses an absolute to turn one event into a fixed identity."),
  flag("you always do this", "Generalisation", "medium", "Transforms a specific incident into a permanent trait."),
  flag("you never do anything for me", "Generalisation", "medium", "Erases contributions through an accusatory absolute."),
  flag("you're always the same", "Generalisation", "medium", "Locks you into a stable negative label."),
  flag("you'll never change", "Devaluation", "high", "Denies the possibility of growth and reinforces helplessness."),
  flag("who else would want you", "Devaluation", "high", "Targets self-worth and fear of abandonment."),
  flag("you're lucky to have me", "Devaluation", "high", "Creates an emotional hierarchy and undermines confidence."),
  flag("you'll never find anyone like me", "Dependency", "high", "Uses fear of the future to keep you from leaving."),
  flag("no one else will want you", "Intimidation", "high", "Threatens emotional isolation to restrict freedom of choice."),
  flag("you'll regret it if you leave", "Threat", "high", "Links leaving the relationship with intimidating consequences."),
  flag("if you leave me I'll kill myself", "Emotional blackmail", "high", "Uses a threat of self-harm to block free choice; immediate support is important."),
  flag("you'd better be careful", "Threat", "high", "Implies consequences without stating them openly."),
  flag("you don't know what I'm capable of", "Threat", "high", "Evokes possible retaliation to create fear."),
  flag("you'll pay for this", "Threat", "high", "Promises direct retaliation."),
  flag("this isn't over", "Threat", "medium", "Can imply future retaliation or escalation."),
  flag("you'll see what happens", "Threat", "medium", "Keeps a consequence vague to heighten anxiety."),
  flag("I'm only trying to help", "False concern", "low", "May disguise control or criticism as unsolicited help."),
  flag("I'm doing this for your own good", "False concern", "medium", "Justifies an imposition by claiming it benefits you."),
  flag("you'll thank me one day", "False concern", "medium", "Assumes the speaker knows your needs better than you do."),
  flag("just trust me", "Pressure", "medium", "Asks for blind trust and discourages legitimate questions."),
  flag("don't ask questions", "Control", "high", "Prevents you from seeking information or clarification."),
  flag("don't complicate things", "Silencing", "medium", "Frames necessary discussion as an unnecessary problem."),
  flag("just drop it", "Silencing", "low", "Can close an issue without listening or resolution."),
  flag("I don't want to talk about it", "Avoidance", "low", "When repeated, it can block any attempt to address a problem."),
  flag("there's no point talking about it", "Avoidance", "medium", "Declares dialogue useless before it can happen."),
  flag("as long as you live under my roof", "Control", "high", "Uses housing or material support as leverage for obedience."),
  flag("I'm the one who pays", "Financial control", "high", "Uses money to claim total decision-making power."),
  flag("you don't need to work", "Financial control", "medium", "May discourage financial autonomy and increase dependence."),
  flag("I'll manage the money", "Financial control", "high", "Unilaterally excludes another person from financial decisions."),
  flag("tell me what you spent", "Financial control", "medium", "Can become financial surveillance when not mutual and agreed."),
  flag("you embarrass me", "Shaming", "medium", "Uses shame to control expression or behaviour."),
  flag("you're making me look bad", "Shaming", "medium", "Uses reputation to demand conformity."),
  flag("what will people think", "Social pressure", "low", "Invokes outside judgement to limit a personal choice."),
  flag("a normal person wouldn't do that", "Normalisation", "high", "Defines normality in order to pathologise a different choice."),
  flag("you're the only one who thinks that", "Social pressure", "medium", "Isolates your opinion by presenting it as abnormal."),
  flag("grow up", "Devaluation", "medium", "Reduces a position to immaturity instead of discussing it."),
  flag("act like an adult", "Devaluation", "medium", "Uses a judgement about maturity to shut down discussion."),
  flag("stop playing the victim", "Victim blaming", "high", "Dismisses the report of harm as an opportunistic strategy."),
  flag("you just want attention", "Invalidation", "high", "Assigns a motive in order to dismiss a request for help."),
  flag("you're selfish", "Guilt", "medium", "May turn a personal boundary into a moral failing."),
  flag("you only think about yourself", "Guilt", "medium", "Generalises in order to shame a choice or boundary."),
  flag("don't be selfish", "Pressure", "medium", "Uses a moral label to gain compliance."),
  flag("if you were a good person", "Moral blackmail", "high", "Makes moral worth conditional on obedience."),
  flag("a good partner would do it", "Role pressure", "high", "Imposes a relationship role to obtain compliance."),
  flag("real men don't cry", "Role pressure", "high", "Uses a gender stereotype to suppress emotion."),
  flag("a real woman should", "Role pressure", "high", "Uses a gender stereotype to dictate behaviour."),
  flag("don't be weak", "Shaming", "medium", "Presents vulnerability or help-seeking as a defect."),
  flag("I never make mistakes", "Moral superiority", "medium", "Makes equal discussion of responsibility impossible."),
  flag("you're the problem", "Blame", "high", "Reduces a complex dynamic to a personal defect."),
  flag("the problem is you", "Blame", "high", "Assigns all responsibility to the person rather than behaviours."),
  flag("it's impossible to talk to you", "Silencing", "medium", "Ends dialogue by placing all responsibility for its failure on you."),
  flag("you don't deserve an explanation", "Punishment", "high", "Withholds information deliberately as a form of power."),
  flag("I'll ignore you until you understand", "Punishment", "high", "Uses silence as punishment and control."),
  flag("I'm not speaking to you", "Punishment", "medium", "May threaten emotional withdrawal to obtain compliance."),
  flag("do whatever you want", "Passive aggression", "low", "In context, can signal punitive disapproval rather than consent."),
  flag("good for you", "Passive aggression", "low", "When sarcastic, it dismisses a choice instead of discussing it."),
  flag("it was obvious", "Devaluation", "low", "Makes a difficulty look like proof of incompetence."),
  flag("you should know that already", "Devaluation", "medium", "Uses an unstated expectation to generate shame."),
  flag("you're not good enough", "Devaluation", "high", "Makes a sweeping judgement of inadequacy."),
  flag("you disappoint me", "Guilt", "medium", "May turn an autonomous choice into emotional failure."),
  flag("I expected better from you", "Guilt", "medium", "Uses personal expectations to induce shame or conformity."),
  flag("if you keep this up I'll leave", "Ultimatum", "high", "Uses the threat of abandonment to control behaviour."),
  flag("I can replace you anytime", "Intimidation", "high", "Threatens replacement to create insecurity and obedience."),
  flag("you're worthless", "Devaluation", "high", "Directly attacks personal worth."),
];

const expandedRedFlagsEn: RedFlag[] = [
  ...group([
    "you don't understand anything", "you haven't understood a thing", "this is too difficult for you", "you just don't get it",
    "do I have to explain the simplest things to you", "you don't even know that", "you're completely ignorant", "you speak without knowing",
    "you have no idea what you're talking about", "study before you speak", "educate yourself before opening your mouth", "you lack basic knowledge",
    "you don't have the tools to understand", "you're not intelligent enough", "this discussion is beyond you", "let the knowledgeable people speak",
    "this is beyond your abilities", "your understanding is very limited", "you can't follow a simple argument", "we have to start from the alphabet with you",
    "you don't understand the basics", "you have no expertise", "your opinion is worthless because you know nothing", "anything can confuse you",
    "you're slow to understand", "you don't know how to reason", "you have no critical thinking", "you believe everything you hear",
    "you're not capable of judging this", "you don't have the necessary background", "this conversation is too advanced for you",
    "leave this to people who understand it", "you're intellectually out of your depth", "you couldn't understand even if I explained it",
  ], "Intellectual belittling", "high", "Attacks intelligence, education or comprehension to create inferiority and invalidate the person's position."),

  ...group([
    "what a stupid question", "do you hear yourself", "did you really just say that", "that's the most ridiculous thing I've heard",
    "it's funny when you try to explain yourself", "I can't take you seriously", "you're a joke", "you make a fool of yourself",
    "how embarrassing for you", "keep making a fool of yourself", "everyone is laughing at you", "just look at yourself",
    "you sound like a child", "you talk like a child", "that's kindergarten logic", "it's cute when you try to think",
    "do you want applause", "congratulations on that brilliant idea", "I'll remember that one for a laugh", "you have no idea how funny you sound",
    "listening to you is embarrassing", "you're humiliating yourself", "you have no dignity", "you look pathetic when you insist",
    "it's almost entertaining watching you try", "you can't even defend yourself", "you're a parody of yourself", "what a pathetic display",
    "don't make me laugh", "stop before you embarrass yourself more", "all you're missing is a clown nose", "that was your argument",
    "people laugh when you leave the room", "you've become the punchline", "this is comedy gold",
  ], "Ridicule", "high", "Uses mockery and humiliation to move attention from the issue to the person's perceived worth."),

  ...group([
    "let me finish and then maybe you can speak", "don't interrupt while I'm explaining", "I'm speaking now", "your turn is over",
    "I didn't give you permission to speak", "shut up and listen", "close your mouth", "stop talking", "I don't want to hear any more",
    "this discussion ends now", "there's nothing more to say", "you don't deserve an answer", "I won't waste time answering you",
    "you're not worth listening to", "your opinion wasn't requested", "nobody asked you", "stop changing the subject",
    "stop challenging everything", "don't argue with everything I say", "don't raise objections", "spare me your explanations",
    "don't justify yourself", "don't start with your stories", "save your point of view", "listen without talking back",
    "you don't always need the last word", "I'll tell you when you can answer", "this isn't a conversation", "there is nothing to discuss",
    "the subject is closed", "I won't listen to any more excuses", "your voice isn't needed here", "keep your thoughts to yourself",
    "you've said more than enough", "I decide when this conversation is finished",
  ], "Interruption and silencing", "high", "Prevents dialogue or controls who may speak, reducing the ability to express a view or disagree."),

  ...group([
    "I know far more than you", "I have much more experience than you", "trust me I understand this better", "you can't compete with me",
    "I'm on another level", "you're not on my level", "I'm always one step ahead", "you'd all be lost without me",
    "I'm the competent one here", "I'm the only one here who can think", "if it works it's because of me", "I had to fix everything myself",
    "as always I have to save the situation", "nobody does it as well as I do", "I don't need your advice", "I have nothing to learn from you",
    "you should learn from me", "you should be grateful to have me", "I see things you can't see", "I'm too advanced to be understood",
    "intelligent people understand me", "I always get what I want", "I'm used to dealing with better people", "I won't lower myself to this discussion",
    "talking to you is a waste of my talent", "my time is worth more than yours", "I bring value and you bring problems", "everyone depends on me",
    "I'm indispensable", "nothing would exist without my contribution", "I'm the one holding everything together", "I'm the smartest person in the room",
    "people like you should listen to people like me", "my judgement is naturally superior",
  ], "Superiority and self-aggrandisement", "medium", "Creates a hierarchy by claiming superiority, indispensability or special entitlement in order to diminish others."),

  ...group([
    "you're confusing the facts", "your version makes no sense", "you've made up a whole story", "you see problems where none exist",
    "you interpret everything incorrectly", "your perception is distorted", "you're not thinking clearly", "you can't trust your own judgement",
    "you need to trust my memory", "I know what happened better than you", "you've completely changed the story", "you're rewriting what happened",
    "nobody saw what you claim happened", "you're the only one who remembers it that way", "you have selective memory", "you confuse dreams with reality",
    "you're creating a problem out of nothing", "you invent intentions that aren't there", "you need to be evaluated", "you're unstable",
    "your accounts are never reliable", "your emotions stop you understanding", "you can't reason when you're like this", "you're losing touch with reality",
    "you can't really know what you heard", "you convince yourself of things that never happened", "your mind plays tricks on you",
    "you're too confused to remember", "I did none of the things you claim", "that's only your imagination", "you've always struggled to separate fact from fiction",
    "I know your experience better than you do", "your version keeps changing", "you're inventing memories", "you need me to tell you what's real",
  ], "Gaslighting and reality", "high", "Systematically questions memory, perception or sanity in order to impose a dominant version of reality."),

  ...group([
    "if you say no it means you don't care", "if you loved me you wouldn't hesitate", "a loving person wouldn't set boundaries",
    "you break my heart every time", "you're abandoning me when I need you most", "you're responsible for my happiness", "I'll be devastated unless you agree",
    "you can't do this to me", "not after everything we've been through", "you're betraying me", "you're destroying our family",
    "do you really want to hurt me", "if you refuse I'll never forgive you", "prove that you care", "make this small sacrifice for me",
    "I would do it for you without thinking", "obviously I care more than you do", "I expected you to choose me", "choose yourself and you'll lose me",
    "I can't believe you can be so cold", "you make me feel like I mean nothing", "after this I don't know who you are", "you ruined my whole day",
    "it will be your fault if I suffer", "I won't sleep because of you", "I'll always remember that you said no", "this proves how little you love me",
    "if you cared you'd make the effort", "I wouldn't ask if it wasn't important", "you owe me at least one chance", "you can't deny me this too",
    "you're the only person who can save me", "my happiness is in your hands", "a no from you is an act of cruelty",
  ], "Emotional blackmail and guilt", "high", "Turns affection, suffering or emotional debt into leverage to obtain consent and override boundaries."),

  ...group([
    "do exactly what I tell you", "don't make decisions without me", "talk to me before you decide", "I need to approve every choice",
    "you can't decide on your own", "I know what's best for you", "let the person who knows better decide", "don't go anywhere without telling me",
    "you must answer me immediately", "I want all your passwords", "never lock your phone", "show me your messages", "make the call in front of me",
    "put the call on speaker", "don't delete your history", "I won't accept you having secrets", "you can't have private spaces",
    "I need to know everyone you see", "don't go out with them", "don't speak to that person", "don't post that photo",
    "take that off", "don't dress like that when I'm not there", "don't spend money without asking", "give me access to your account",
    "I'll control your salary", "you don't need your own bank account", "don't sign anything without me", "don't accept that job",
    "don't study that subject", "don't travel without my approval", "the rules are mine", "I'm in charge in this house",
    "you report to me about everything", "your privacy ends where my suspicion begins",
  ], "Coercive control", "high", "Restricts autonomy, privacy, relationships or resources through surveillance, permission and enforced obedience."),

  ...group([
    "those people are using you", "your friends don't really care about you", "your family doesn't understand you", "they fill your head with lies",
    "you've changed since seeing them", "you choose them over me", "if you go to them don't come back", "I don't want that person in our home",
    "your colleagues laugh at you", "nobody at work respects you", "I'm the only one on your side", "other people are trying to separate us",
    "don't discuss our problems outside", "a therapist would turn you against me", "you don't need a therapist", "don't involve your family",
    "don't call your friends", "don't ask anyone for advice", "single people are jealous of us", "anyone telling you to leave is jealous",
    "everyone is manipulating you except me", "only with me can you be yourself", "nobody outside would accept you", "other people only see the worst in you",
    "I'll protect you from the world", "don't trust anyone except me", "don't tell the doctor about this", "don't go to that appointment",
    "delete that contact", "block that person", "your support network is the real problem", "your best friend is poisoning your mind",
    "they want to steal you from me", "you don't need anyone else when you have me",
  ], "Social isolation", "high", "Discredits or restricts support networks to increase dependence, secrecy and vulnerability."),

  ...group([
    "it's obvious to everyone", "any reasonable person would agree", "you're the only one who doesn't understand", "no sane person thinks that way",
    "the facts speak for themselves", "there's no need to prove it", "everyone knows I'm right", "you can't deny the obvious",
    "if you disagree you're being dishonest", "anyone who criticises me is jealous", "everyone who knows me knows the truth",
    "there's no need to hear the other side", "there's only one truth and it's mine", "there are no sensible alternatives",
    "if you were objective you'd agree with me", "your disagreement proves you didn't understand", "contradicting me proves my point",
    "the fact you're defending yourself proves you're guilty", "if you don't answer that means I'm right", "anything you say will be an excuse",
    "you cannot win this argument", "I've already proved everything", "there's no room for opinions", "this isn't an opinion it's a fact",
    "I don't have to show you evidence", "it's your job to prove me wrong", "the majority can't be wrong", "intelligent people agree with me",
    "only someone with something to hide would object", "your tone proves I'm right", "if you're angry I must have hit a nerve",
    "if you're crying it's because you know it's true", "your reaction is my evidence", "your denial is exactly what a guilty person would say",
  ], "False logic and consensus", "medium", "Presents opinions as inevitable facts or treats the other person's reaction as proof, making disagreement impossible."),

  ...group([
    "remember I can make your life difficult", "I know exactly how to hurt you", "I know all your weak spots", "don't challenge me",
    "don't test me", "don't make me become cruel", "I could tell everyone everything", "I know things you don't want exposed",
    "I can ruin your reputation", "I can get you fired", "I can take everything away from you", "nobody will come to help you",
    "you'd better obey", "this is your last chance", "choose your next words carefully", "if you speak there will be consequences",
    "you don't know what trouble you're getting into", "I can reach you wherever you go", "you'll never get rid of me", "I'll be watching you",
    "I know where to find you", "don't think you're safe", "I'll make you regret this bitterly", "the people you love will pay too",
    "don't provoke a reaction you can't handle", "don't say I didn't warn you", "you still have time to make this right", "I'm letting it go this time",
    "next time will be worse", "don't make me lose my patience", "you know what happens when I'm angry", "I won't be responsible for what I do",
    "I might lose control", "keep pushing and see what happens", "one call from me can ruin everything",
  ], "Threat and intimidation", "high", "Evokes harm, retaliation or loss of control to create fear and obtain obedience."),

  ...group([
    "yeah sure", "okay champion", "what a great expert", "thank goodness you're here", "now you've solved everything",
    "truly brilliant", "you're such a genius", "round of applause", "do you want a medal", "brilliant as always",
    "I knew you'd get it wrong", "I'm surprised you managed it", "for once you did something right", "don't get carried away",
    "don't think you're suddenly good at this", "maybe one day you'll understand", "we'll talk when you grow up", "I'd explain but it would be pointless",
    "I won't waste words on you", "your innocence is adorable", "ignorance is bliss", "keep living in your little world",
    "you're adorable when you're convinced", "your confidence is almost touching", "okay professor", "whatever you say genius",
    "congratulations you discovered the obvious", "that must have taken all your brainpower", "look who finally caught up",
    "should we celebrate your basic competence", "you're almost convincing when you pretend to know", "how brave of you to have an opinion",
    "that's cute coming from you", "I love how seriously you take yourself", "keep talking this is entertaining",
  ], "Sarcasm and contempt", "medium", "Uses irony and false praise to humiliate, diminish competence or avoid a direct response."),

  ...group([
    "you're not cut out for this job", "you're easily replaceable here", "there are a hundred people better than you", "you should thank me for this opportunity",
    "without my recommendation you wouldn't be here", "your position depends on me", "don't try to advance against me", "I can block your career",
    "I decide who gets heard", "don't bring ideas without going through me", "this idea is mine now", "let me present it",
    "you wouldn't know how to sell it", "you're not ready for visibility", "don't speak in meetings unless I ask you", "don't contradict me in front of others",
    "smile and stop causing problems", "I'll report that you're not a team player", "people who complain don't last here", "you need a thick skin to work here",
    "you're not resilient enough", "this environment is for strong people", "overtime proves loyalty", "if you cared about the project you'd stay",
    "your private life isn't my problem", "everyone makes sacrifices except you", "don't expect recognition", "you should be grateful to have a job",
    "merit isn't enough you need to please me", "I control your performance review", "I can make your contribution invisible", "nobody will notice if you leave",
    "your promotion depends on your attitude toward me", "keep quiet if you want a future here", "I'll make sure you never work in this industry again",
  ], "Workplace manipulation", "high", "Uses power, precarity, visibility or career prospects to impose silence, steal credit or demand involuntary availability."),

  ...group([
    "you're too ugly to expect better", "you should be grateful anyone looks at you", "you're not attractive anymore", "you can't wear that with your body",
    "who are you trying to impress dressed like that", "without makeup you're unrecognisable", "with makeup you look fake", "you've gained weight and it shows",
    "you're too thin to be attractive", "at your age you should cover up", "you're too old to dress like that", "nobody wants to see your body",
    "I accept you despite your appearance", "you could look good if you listened to me", "other people judge how you look", "you embarrass me dressed like that",
    "you're not the kind of person people notice", "don't get carried away by one compliment", "you're attractive but not enough", "fix yourself before we go out",
    "you look neglected", "your appearance reflects badly on me", "you'll never find someone who accepts your flaws", "I'm out of your league",
    "you should be grateful I overlook your flaws", "you'd look better if you did what I said", "you don't have the body for that",
    "people are only being polite when they compliment you", "your best years are behind you", "nobody else would find you desirable",
    "you need my approval before changing your appearance", "your body is becoming a problem for me", "I decide what looks good on you",
  ], "Body shaming", "high", "Targets appearance, age or body to create shame, dependence and control over self-expression."),

  ...group([
    "you're too emotional to decide", "crying makes you lose credibility", "your anxiety makes everything unreliable", "you use emotion to manipulate people",
    "you choose to feel bad", "your sadness ruins everything", "nobody has time for your problems", "you're exhausting to be around",
    "you need to stop feeling that way", "you have no reason to be sad", "other people have it worse so be quiet", "your fear is ridiculous",
    "asking for help makes you weak", "you go to therapy because you're broken", "only an unstable person would react this way",
    "I can't trust someone with your issues", "your diagnosis is just an excuse", "take your medication and stop complaining",
    "you're mentally ill", "your emotions don't count as facts", "if you were stronger you wouldn't need help", "you enjoy being miserable",
    "you're looking for sympathy", "you want everyone to take care of you", "you're addicted to attention", "you can't make decisions in this state",
    "I need to protect you from yourself", "you can't manage your own life", "your therapist doesn't know you like I do",
    "I know what's best for your mental health", "your vulnerability makes you incompetent", "your panic proves you can't be trusted",
    "stop using your trauma as an excuse", "your feelings are a burden to everyone", "you need permission before changing treatment",
  ], "Emotional and mental-health stigma", "high", "Uses emotion, vulnerability or mental health to remove credibility, autonomy and the right to seek support."),
];

export const redFlagsEn: RedFlag[] = Array.from(
  new Map([...baseRedFlagsEn, ...expandedRedFlagsEn].map((entry) => [entry.phrase.toLocaleLowerCase("en"), entry])).values(),
);
